# Generated by Django 2.2 on 2019-04-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('local', models.CharField(max_length=255)),
                ('assunto', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=255)),
                ('dist', models.CharField(max_length=255)),
            ],
        ),
    ]
